from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from src.francophonia import BUILD_PATH

# Create the FastAPI application
app = FastAPI()

# Mount the directory generated by MkDocs
app.mount("/", StaticFiles(directory=BUILD_PATH, html=True), name="root")
