from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from src.francophonia import PROJECT_PATH

app = FastAPI()

# Mount the directory generated by MkDocs
docs_path = PROJECT_PATH / "site"
app.mount("/", StaticFiles(directory=docs_path, html=True), name="docs")
