site_name: FrancophonIA
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: True
theme:
  name: "material"
  # logo: "images/logo.png"
  palette:
    scheme: default
    primary: "indigo"
    accent: "indigo"
  font:
    text: "Roboto"
    code: "Roboto Mono"