site_name: FrancophonIA

repo_name: "Athroniaeth/francophonia"
repo_url: "https://github.com/Athroniaeth/francophonia"
edit_uri: "edit/main/docs/"

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences  # Gère les blocs de code avancés avec des onglets ou titres
  - pymdownx.snippets  # Inclut des fichiers externes ou du code réutilisable
  - pymdownx.details  # Ajoute des sections repliables pour du contenu additionnel
  - pymdownx.highlight  # Améliore la coloration syntaxique
  - pymdownx.emoji  # Permet d'utiliser des émojis dans le contenu
  - pymdownx.highlight:
      use_pygments: True
  - toc:
      permalink: True
  # pymdownx.tabbed # Gère les blocs de code avancés avec des onglets ou titres
  - pymdownx.blocks.tab:  # Inclut les fenêtre (tab) pour les exemples de code
      alternate_style: true  # https://github.com/squidfunk/mkdocs-material/issues/1762


plugins:
  - search:
  - tags:
      tags_file: tags.md
  - macros:  # Permet d'utiliser des macros pour des inclusions dynamiques
      module_name: docs/macro
  - blog:
      archive_date_format: MMMM yyyy  # Reformat the date in indexes blog
      pagination_per_page: 5  # Number of articles per page maximum

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Athroniaeth/francophonia

    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/km5gJXQxbM

  copyright:
    text: "© 2024 FrancophonIA. Tous droits réservés."

  tags:
    Outils: tool
    Projets: project

theme:
  name: "material"
  logo: "/__static/img/logo.png"
  favicon: "/__static/img/favicon.png"

  features:
      - navigation.tabs  # Add tabs to the navigation bar
      - content.action.edit  # Add an edit button (redirect to github edit page)

  palette:
    scheme: default
    primary: "indigo"
    accent: "indigo"

  font:
    text: "Roboto"
    code: "Roboto Mono"

extra_css: [__static/css/extra.css]