site_name: FrancophonIA
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: True
  - pymdownx.highlight:
      use_pygments: True
  - pymdownx.superfences
theme:
  name: "material"
  logo: "/static/logo.png"
  palette:
    scheme: default
    primary: "indigo"
    accent: "indigo"
  font:
    text: "Roboto"
    code: "Roboto Mono"