site_name: FrancophonIA

repo_name: "Athroniaeth/francophonia"
repo_url: "https://github.com/Athroniaeth/francophonia"
edit_uri: "edit/main/docs/"

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: True
  - pymdownx.highlight:
      use_pygments: True
  - pymdownx.superfences

plugins:
  - blog:
  - search:
  - tags:
      tags_file: tags.md

extra:
  tags:
    Outils: tool
    Projets: project

theme:
  name: "material"
  logo: "/__static/img/logo.png"
  favicon: "/__static/img/favicon.png"

  features:
      - navigation.tabs  # Add tabs to the navigation bar
      - content.action.edit  # Add an edit button (redirect to github edit page)

  palette:
    scheme: default
    primary: "indigo"
    accent: "indigo"

  font:
    text: "Roboto"
    code: "Roboto Mono"

extra_css: [__static/css/extra.css]