site_name: FrancophonIA

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: True
  - pymdownx.highlight:
      use_pygments: True
  - pymdownx.superfences

plugins:
  - search:
  - tags:
      tags_file: tags.md

extra:
  tags:
    Outils: tool
    Projets: project

theme:
  name: "material"
  logo: "/static/logo.png"
  favicon: "/static/favicon.png"

  features:
      - navigation.tabs

  palette:
    scheme: default
    primary: "indigo"
    accent: "indigo"

  font:
    text: "Roboto"
    code: "Roboto Mono"